
CREATE TABLE CATEGORY (
CATEGORY_ID INT,
CATEGORY_NAME VARCHAR(50),
PRIMARY KEY (CATEGORY_ID)
)

CREATE TABLE PRODUCTS(
PRODUCT_ID INT,
CATEGORY_ID INT,
PRODUCT_NAME VARCHAR(50),
PRODUCT_DESCRIPTION VARCHAR(100),
TOTAL_QUANTITY DECIMAL(2,2),
PRIMARY KEY(PRODUCT_ID),
FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (CATEGORY_ID)
) 

CREATE TABLE WHEREHOUSE(
WHEREHOUSE_ID INT,
WHEREHOUSE_NAME VARCHAR(50),
WHEREHOUSE_ADDRESS VARCHAR(100),
PRIMARY KEY (WHEREHOUSE_ID),
)

CREATE TABLE STORAGE(
STORAGE_ID INT,
STORAGE_NAME VARCHAR(50),
PARTIAL_QUANTITY DECIMAL(2,2),
PRODUCT_ID INT,
WHEREHOUSE_ID INT,
PRIMARY KEY(STORAGE_ID),
FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS (PRODUCT_ID),
FOREIGN KEY(WHEREHOUSE_ID) REFERENCES WHEREHOUSE (WHEREHOUSE_ID)
)

CREATE TABLE INOUTS(
INOUT_ID INT,
INOUT_DATE DATETIME,
QUALITY VARCHAR(100),
STORAGE_ID INT
PRIMARY KEY (INOUT_ID),
FOREIGN KEY(|) REFERENCES STORAGE (STORAGE_ID)
)
